apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:f95e4f1454deca015390b9dcdd875d58fa36a9ef4228f1794bc6cdb9376cf1ad
  name: quay.io/bluesman/vote-api
  newName: quay.io/bluesman/vote-api
- digest: sha256:72d60104ad6d435fdd6acf88930328f6ce3993c5597aabf554482d3410becf2a
  name: quay.io/bluesman/vote-ui
  newName: quay.io/bluesman/vote-ui
- digest: sha256:bd355587d2ddcbcd1af5ca90207fe6e814b37996228c12eee849c5b2e82f79d3
  name: quay.io/saroonga/vote-api
  newName: quay.io/saroonga/vote-api
- digest: sha256:c60395a85c7b5da4f623a29ed955d18b7403e354358272da9b7628593043ddc2
  name: quay.io/saroonga/vote-ui
  newName: quay.io/saroonga/vote-ui
